# Generated by Django 5.0.1 on 2024-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="creation_date",
            field=models.DateField(null=True),
        ),
    ]
