# Generated by Django 5.0.1 on 2024-01-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_car_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(default="Default description"),
        ),
    ]
