# Generated by Django 5.0.1 on 2024-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_car_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="market_segment",
            field=models.CharField(
                choices=[
                    ("A", "mini car"),
                    ("B", "small car"),
                    ("C", "medium car"),
                    ("D", "large car"),
                    ("F", "luxury car"),
                    ("S", "sport car"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
