# Generated by Django 5.0.1 on 2024-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_car_market_segment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("datetime_sent", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
