# Generated by Django 5.0.1 on 2024-01-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
